ceiling_base_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - long_joint
    - short_joint
  gains:
    long_joint: {p: 100,  d: 50, i: 1, i_clamp: 1}
    short_joint: {p: 100,  d: 50, i: 1, i_clamp: 1}

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0
